import { useDatabase } from '@/hooks/useDatabase';
import { getStock, refillStock, Stock, getAllBatches, StockBatch } from '@/services/db';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { StatusBar } from 'expo-status-bar';
import React, { useEffect, useState, useMemo } from 'react';
import { Alert, FlatList, Modal, Share, StyleSheet, Text, TextInput, TouchableOpacity, View, ScrollView } from 'react-native';
import { toggleStockTracking } from '@/services/db';
import Animated, { FadeInRight, FadeInDown } from 'react-native-reanimated';

export default function StockScreen() {
    const { isReady, refreshData, medications } = useDatabase();
    const [stockItems, setStockItems] = useState<(Stock & { name: string })[]>([]);
    const [isModalVisible, setIsModalVisible] = useState(false);
    const [refillAmount, setRefillAmount] = useState('');
    const [refillExpiry, setRefillExpiry] = useState('');
    const [selectedItem, setSelectedItem] = useState<(Stock & { name: string }) | null>(null);
    const [activeFilter, setActiveFilter] = useState<'all' | 'low' | 'expired'>('all');
    const [batches, setBatches] = useState<StockBatch[]>([]);
    const [searchQuery, setSearchQuery] = useState('');

    useEffect(() => {
        if (isReady) {
            loadStock();
        }
    }, [isReady]);

    const loadStock = async () => {
        const [data, batchData] = await Promise.all([getStock(), getAllBatches()]);
        setStockItems(data);
        setBatches(batchData);
    };

    const stats = useMemo(() => {
        const total = stockItems.length;
        const low = stockItems.filter(i => i.quantity <= i.threshold).length;
        
        const today = new Date();
        today.setHours(0,0,0,0);

        // Count unique medications that have at least one expired batch (matches filter logic)
        const expired = stockItems.filter(item => {
            const itemBatches = batches.filter(b => b.medicationId === item.medicationId);
            return itemBatches.some(b => {
                const [y, m, d] = b.expiryDate.split('-').map(Number);
                return new Date(y, m - 1, d) < today;
            });
        }).length;

        return { total, low, expired };
    }, [stockItems, batches]);

    const filteredItems = stockItems.filter(item => {
        const matchesSearch = item.name.toLowerCase().includes(searchQuery.toLowerCase());
        
        let matchesFilter = true;
        if (activeFilter === 'low') {
            matchesFilter = item.quantity <= item.threshold;
        } else if (activeFilter === 'expired') {
            const itemBatches = batches.filter(b => b.medicationId === item.medicationId);
            const today = new Date();
            today.setHours(0,0,0,0);
            matchesFilter = itemBatches.some(b => {
                const [y, m, d] = b.expiryDate.split('-').map(Number);
                return new Date(y, m - 1, d) < today;
            });
        }
        
        return matchesSearch && matchesFilter;
    });

    const untrackedMedications = medications.filter(med => 
        !stockItems.some(s => s.medicationId === med.id) &&
        med.name.toLowerCase().includes(searchQuery.toLowerCase())
    );

    const handleEnableTracking = async (medId: number) => {
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
        await toggleStockTracking(medId, true);
        await refreshData();
        loadStock();
    };

    const handleShareShoppingList = async () => {
        const lowStockItems = stockItems.filter(item => item.quantity <= item.threshold);
        if (lowStockItems.length === 0) {
            Alert.alert('All Set!', 'You have no items below their threshold.');
            return;
        }

        const list = lowStockItems.map(s => `• ${s.name} (Current: ${s.quantity}, Min: ${s.threshold})`).join('\n');
        try {
            await Share.share({
                title: 'Medicine Shopping List',
                message: `🛒 *Medicine Shopping List*\n-------------------------\n${list}\n-------------------------\nGenerated by your Medicine Tracker.`,
            });
        } catch {
            Alert.alert('Error', 'Failed to share shopping list');
        }
    };

    const handleShare = async () => {
        const stockReport = stockItems.map(s => `${s.name}: ${s.quantity} units (Threshold: ${s.threshold})`).join('\n');
        try {
            await Share.share({
                message: `Medicine Stock Report:\n\n${stockReport}`,
            });
        } catch {
            Alert.alert('Error', 'Failed to share report');
        }
    };

    const handleRefill = (item: Stock & { name: string }) => {
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
        setSelectedItem(item);
        setRefillAmount('');
        setRefillExpiry('');
        setIsModalVisible(true);
    };

    const confirmRefill = async () => {
        const qty = parseInt(refillAmount || '0');
        if (isNaN(qty) || qty <= 0) {
            Alert.alert('Invalid Amount', 'Please enter a valid number.');
            return;
        }

        const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
        if (!dateRegex.test(refillExpiry)) {
            Alert.alert('Invalid Date', 'Please enter a date in YYYY-MM-DD format.');
            return;
        }

        if (selectedItem) {
            await refillStock(selectedItem.medicationId, qty, refillExpiry);
            setIsModalVisible(false);
            setSelectedItem(null);
            await refreshData();
            loadStock();
        }
    };

    const renderStockItem = ({ item }: { item: (Stock & { name: string }) }) => {
        const isLow = item.quantity <= item.threshold;
        const itemBatches = batches.filter(b => b.medicationId === item.medicationId);
        const sortedBatches = [...itemBatches].sort((a, b) => new Date(a.expiryDate).getTime() - new Date(b.expiryDate).getTime());
        
        const getBatchStatus = (dateStr: string) => {
            const today = new Date();
            today.setHours(0,0,0,0);
            const [y, m, d] = dateStr.split('-').map(Number);
            const expDate = new Date(y, m - 1, d);
            const daysToExpiry = Math.ceil((expDate.getTime() - today.getTime()) / (1000 * 3600 * 24));
            if (daysToExpiry < 0) return { color: '#EF4444', label: 'Expired' };
            if (daysToExpiry <= 30) return { color: '#F59E0B', label: 'Expiring Soon' };
            return { color: '#10B981', label: 'Good' };
        };

        return (
            <View style={styles.stockCard}>
                <View style={styles.cardHeader}>
                    <View style={styles.stockInfo}>
                        <Text style={styles.medName}>{item.name}</Text>
                        <Text style={[styles.qtyText, isLow && styles.lowQty]}>
                            {item.quantity} units total
                        </Text>
                    </View>
                    {isLow && (
                        <View style={styles.warningBadge}>
                            <Ionicons name="warning" size={16} color="#B45309" />
                            <Text style={styles.warningText}>Low Stock</Text>
                        </View>
                    )}
                </View>

                {sortedBatches.length > 0 && item.quantity > 0 && (
                    <View style={styles.batchesContainer}>
                        <View style={styles.progressBar}>
                            {sortedBatches.map(batch => {
                                const widthPct = Math.max(2, (batch.quantity / item.quantity) * 100);
                                const status = getBatchStatus(batch.expiryDate);
                                return (
                                    <View 
                                        key={batch.id} 
                                        style={[styles.progressSegment, { width: `${widthPct}%`, backgroundColor: status.color }]} 
                                    />
                                );
                            })}
                        </View>
                        <View style={styles.batchesList}>
                            {sortedBatches.map(batch => {
                                const status = getBatchStatus(batch.expiryDate);
                                return (
                                    <View key={batch.id} style={styles.batchRow}>
                                        <View style={[styles.batchDot, { backgroundColor: status.color }]} />
                                        <Text style={styles.batchQuantityText}>{batch.quantity} pills</Text>
                                        <Text style={styles.batchExpiryText}>exp. {batch.expiryDate}</Text>
                                        {status.label !== 'Good' && (
                                            <View style={[styles.batchTag, { backgroundColor: status.color + '20' }]}>
                                                <Text style={[styles.batchTagText, { color: status.color }]}>{status.label}</Text>
                                            </View>
                                        )}
                                    </View>
                                );
                            })}
                        </View>
                    </View>
                )}

                <View style={styles.cardFooter}>
                    <View style={styles.thresholdInfo}>
                        <Text style={styles.thresholdLabel}>Threshold:</Text>
                        <Text style={styles.thresholdValue}>{item.threshold} units</Text>
                    </View>
                    <TouchableOpacity style={styles.refillButton} onPress={() => {
                        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
                        handleRefill(item);
                    }}>
                        <Ionicons name="add-circle-outline" size={20} color="#FFF" />
                        <Text style={styles.refillButtonText}>Refill</Text>
                    </TouchableOpacity>
                </View>
            </View>
        );
    };

    return (
        <View style={styles.container}>
            <StatusBar style="dark" />
            <View style={styles.header}>
                <View style={styles.headerTop}>
                    <View style={styles.headerInfo}>
                        <Text style={styles.title}>Inventory</Text>
                        <Text style={styles.subtitle}>Medication Stock</Text>
                    </View>
                    <View style={styles.headerButtons}>
                        <TouchableOpacity style={[styles.headerButton, styles.listBtn]} onPress={() => {
                            Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                            handleShareShoppingList();
                        }}>
                            <Ionicons name="cart-outline" size={18} color="#4F46E5" />
                            <Text style={styles.listBtnText}>List</Text>
                        </TouchableOpacity>
                        <TouchableOpacity style={[styles.headerButton, styles.shareBtn]} onPress={() => {
                            Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                            handleShare();
                        }}>
                            <Ionicons name="share-outline" size={18} color="#10B981" />
                            <Text style={styles.shareBtnText}>Share</Text>
                        </TouchableOpacity>
                    </View>
                </View>

                {/* Search Bar - Extra Feature */}
                <View style={styles.searchContainer}>
                    <Ionicons name="search" size={20} color="#9CA3AF" style={styles.searchIcon} />
                    <TextInput
                        style={styles.searchInput}
                        placeholder="Search medicines..."
                        placeholderTextColor="#9CA3AF"
                        value={searchQuery}
                        onChangeText={setSearchQuery}
                    />
                    {searchQuery.length > 0 && (
                        <TouchableOpacity onPress={() => setSearchQuery('')}>
                            <Ionicons name="close-circle" size={20} color="#9CA3AF" />
                        </TouchableOpacity>
                    )}
                </View>
            </View>

            <View style={styles.filterContainer}>
                <TouchableOpacity
                    style={[styles.filterTab, activeFilter === 'all' && styles.filterTabActive]}
                    onPress={() => {
                        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                        setActiveFilter('all');
                    }}
                >
                    <Text style={[styles.filterTabText, activeFilter === 'all' && styles.filterTabActiveText]}>All Items</Text>
                </TouchableOpacity>
                <TouchableOpacity
                    style={[styles.filterTab, activeFilter === 'low' && styles.filterTabActive]}
                    onPress={() => {
                        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                        setActiveFilter('low');
                    }}
                >
                    <Text style={[styles.filterTabText, activeFilter === 'low' && styles.filterTabActiveText]}>Low Stock</Text>
                    {stats.low > 0 && (
                        <View style={styles.countBadge}>
                            <Text style={styles.countBadgeText}>{stats.low}</Text>
                        </View>
                    )}
                </TouchableOpacity>
                <TouchableOpacity
                    style={[styles.filterTab, activeFilter === 'expired' && styles.filterTabActiveExpired]}
                    onPress={() => {
                        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                        setActiveFilter('expired');
                    }}
                >
                    <Text style={[styles.filterTabText, activeFilter === 'expired' && styles.filterTabActiveText]}>Expired</Text>
                    {stats.expired > 0 && (
                        <View style={[styles.countBadge, { backgroundColor: '#F59E0B' }]}>
                            <Text style={styles.countBadgeText}>{stats.expired}</Text>
                        </View>
                    )}
                </TouchableOpacity>
            </View>

            <FlatList
                data={filteredItems}
                keyExtractor={(item) => item.id.toString()}
                renderItem={renderStockItem}
                contentContainerStyle={styles.list}
                ListHeaderComponent={
                    <View>
                        {/* Stock Stats Dashboard */}
                        <View style={styles.statsContainer}>
                            <TouchableOpacity 
                                style={[styles.statCard, { backgroundColor: '#EEF2FF' }, activeFilter === 'all' && styles.statCardActive]} 
                                onPress={() => {
                                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                                    setActiveFilter('all');
                                }}
                            >
                                <Text style={[styles.statValue, { color: '#4F46E5' }]}>{stats.total}</Text>
                                <Text style={styles.statLabel}>Tracked</Text>
                            </TouchableOpacity>
                            <TouchableOpacity 
                                style={[styles.statCard, { backgroundColor: '#FEF2F2' }, activeFilter === 'low' && styles.statCardActive]} 
                                onPress={() => {
                                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                                    setActiveFilter('low');
                                }}
                            >
                                <Text style={[styles.statValue, { color: '#EF4444' }]}>{stats.low}</Text>
                                <Text style={styles.statLabel}>Low</Text>
                            </TouchableOpacity>
                            <TouchableOpacity 
                                style={[styles.statCard, { backgroundColor: '#FFF7ED' }, activeFilter === 'expired' && styles.statCardActiveExpired]} 
                                onPress={() => {
                                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                                    setActiveFilter('expired');
                                }}
                            >
                                <Text style={[styles.statValue, { color: '#F59E0B' }]}>{stats.expired}</Text>
                                <Text style={styles.statLabel}>Expired</Text>
                            </TouchableOpacity>
                        </View>

                        {untrackedMedications.length > 0 && (
                            <View style={styles.untrackedSection}>
                                <Text style={styles.sectionTitle}>Ready to Track</Text>
                                <ScrollView 
                                    horizontal 
                                    showsHorizontalScrollIndicator={false} 
                                    contentContainerStyle={styles.untrackedList}
                                >
                                    {untrackedMedications.map((med, index) => (
                                        <Animated.View 
                                            key={med.id} 
                                            entering={FadeInRight.delay(index * 100)}
                                        >
                                            <TouchableOpacity 
                                                style={styles.untrackedCard}
                                                onPress={() => handleEnableTracking(med.id)}
                                            >
                                                <View style={[styles.untrackedIcon, { backgroundColor: med.color + '20' }]}>
                                                    <Ionicons name={med.icon as any} size={24} color={med.color} />
                                                </View>
                                                <Text style={styles.untrackedName} numberOfLines={1}>{med.name}</Text>
                                                <View style={styles.enableLabel}>
                                                    <Ionicons name="add" size={12} color="#4F46E5" />
                                                    <Text style={styles.enableText}>Enable</Text>
                                                </View>
                                            </TouchableOpacity>
                                        </Animated.View>
                                    ))}
                                </ScrollView>
                            </View>
                        )}
                        <Text style={styles.sectionTitle}>Inventory List</Text>
                    </View>
                }
                ListEmptyComponent={
                    <View style={styles.emptyState}>
                        <Ionicons name="cube-outline" size={64} color="#CBD5E1" />
                        <Text style={styles.emptyStateTitle}>No stock being tracked</Text>
                        <Text style={styles.emptyStateText}>
                            Enable tracking for your medicines below to manage inventory and get low-stock alerts.
                        </Text>
                    </View>
                }
            />

            <Modal
                visible={isModalVisible}
                transparent={true}
                animationType="fade"
                onRequestClose={() => setIsModalVisible(false)}
            >
                <View style={styles.modalOverlay}>
                    <Animated.View 
                        entering={FadeInDown.duration(300)}
                        style={styles.modalContent}
                    >
                        <View style={styles.modalHeader}>
                            <View style={styles.modalIconBg}>
                                <Ionicons name="add-circle" size={32} color="#4F46E5" />
                            </View>
                            <View>
                                <Text style={styles.modalTitle}>Refill Medicine</Text>
                                <Text style={styles.modalSubtitle}>Update your inventory for {selectedItem?.name}</Text>
                            </View>
                        </View>

                        <View style={styles.modalForm}>
                            <View style={styles.inputGroup}>
                                <Text style={styles.inputLabel}>Quantity to Add</Text>
                                <TextInput
                                    style={styles.modalInput}
                                    placeholder="e.g. 10"
                                    placeholderTextColor="#94A3B8"
                                    value={refillAmount}
                                    onChangeText={setRefillAmount}
                                    keyboardType="number-pad"
                                    autoFocus={true}
                                />
                            </View>

                            <View style={styles.inputGroup}>
                                <Text style={styles.inputLabel}>Expiry Date (YYYY-MM-DD)</Text>
                                <TextInput
                                    style={styles.modalInput}
                                    placeholder="e.g. 2026-12-31"
                                    placeholderTextColor="#94A3B8"
                                    value={refillExpiry}
                                    onChangeText={setRefillExpiry}
                                />
                            </View>
                        </View>

                        <View style={styles.modalButtons}>
                            <TouchableOpacity
                                style={[styles.modalButton, styles.cancelButton]}
                                onPress={() => setIsModalVisible(false)}
                            >
                                <Text style={styles.cancelButtonText}>Cancel</Text>
                            </TouchableOpacity>
                            <TouchableOpacity
                                style={[styles.modalButton, styles.confirmButton]}
                                onPress={confirmRefill}
                            >
                                <Text style={styles.confirmButtonText}>Complete Refill</Text>
                            </TouchableOpacity>
                        </View>
                    </Animated.View>
                </View>
            </Modal>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    header: {
        paddingHorizontal: 20,
        paddingTop: 64,
        paddingBottom: 20,
        backgroundColor: '#FFF',
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    headerInfo: {
        flex: 1,
    },
    title: {
        fontSize: 32,
        fontFamily: 'OutfitBold',
        color: '#111827',
    },
    subtitle: {
        fontSize: 15,
        color: '#6B7280',
        fontFamily: 'Outfit',
        marginTop: 2,
    },
    headerButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    headerButton: {
        flexDirection: 'column',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 12,
        gap: 2,
        borderWidth: 1.5,
        minWidth: 56,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
        borderRadius: 16,
        paddingHorizontal: 12,
        height: 48,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        fontFamily: 'Outfit',
        color: '#111827',
    },
    listBtn: {
        backgroundColor: '#EEF2FF',
        borderColor: '#C7D2FE',
    },
    listBtnText: {
        fontSize: 12,
        color: '#4F46E5',
        fontFamily: 'OutfitBold',
    },
    shareBtn: {
        backgroundColor: '#ECFDF5',
        borderColor: '#A7F3D0',
    },
    shareBtnText: {
        fontSize: 12,
        color: '#10B981',
        fontFamily: 'OutfitBold',
    },
    headerButtonText: {
        color: '#4F46E5',
        fontFamily: 'OutfitBold',
        fontSize: 14,
    },
    filterContainer: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        paddingVertical: 12,
        backgroundColor: '#FFF',
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        gap: 12,
    },
    filterTab: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: '#F3F4F6',
    },
    filterTabActive: {
        backgroundColor: '#4F46E5',
    },
    filterTabActiveExpired: {
        backgroundColor: '#F59E0B',
    },
    filterTabText: {
        fontSize: 14,
        fontFamily: 'Outfit',
        color: '#6B7280',
    },
    filterTabActiveText: {
        color: '#FFF',
        fontFamily: 'OutfitBold',
    },
    countBadge: {
        backgroundColor: '#EF4444',
        minWidth: 18,
        height: 18,
        borderRadius: 9,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 6,
        paddingHorizontal: 4,
    },
    countBadgeText: {
        color: '#FFF',
        fontSize: 10,
        fontFamily: 'OutfitBold',
    },
    list: {
        padding: 20,
    },
    stockCard: {
        backgroundColor: '#FFF',
        borderRadius: 24,
        padding: 20,
        marginBottom: 16,
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.1,
        shadowRadius: 15,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        paddingBottom: 16,
        flexWrap: 'wrap',
        gap: 8,
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 16,
        flexWrap: 'wrap',
        gap: 12,
    },
    stockInfo: {
        flex: 1,
    },
    medName: {
        fontSize: 18,
        fontFamily: 'OutfitBold',
        color: '#111827',
    },
    qtyText: {
        fontSize: 15,
        color: '#6B7280',
        fontFamily: 'Outfit',
        marginTop: 4,
    },
    lowQty: {
        color: '#EF4444',
        fontFamily: 'OutfitBold',
    },
    thresholdInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    thresholdLabel: {
        fontSize: 12,
        color: '#9CA3AF',
        fontFamily: 'Outfit',
    },
    thresholdValue: {
        fontSize: 12,
        color: '#6B7280',
        fontFamily: 'OutfitBold',
        marginLeft: 4,
    },
    refillButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#4F46E5',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
    },
    refillButtonText: {
        color: '#FFF',
        fontFamily: 'OutfitBold',
        fontSize: 14,
        marginLeft: 4,
    },
    warningBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FEF3C7',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
    },
    warningText: {
        marginLeft: 4,
        color: '#B45309',
        fontSize: 12,
        fontFamily: 'OutfitBold',
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 60,
        paddingHorizontal: 40,
    },
    emptyStateTitle: {
        fontSize: 20,
        fontFamily: 'OutfitBold',
        color: '#475569',
        marginTop: 20,
    },
    emptyStateText: {
        fontSize: 15,
        color: '#94A3B8',
        marginTop: 8,
        textAlign: 'center',
        fontFamily: 'Outfit',
    },
    statsContainer: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 24,
    },
    statCard: {
        flex: 1,
        padding: 16,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    statCardActive: {
        borderColor: 'rgba(79, 70, 229, 0.4)',
        elevation: 8,
        transform: [{ scale: 1.05 }],
    },
    statCardActiveExpired: {
        borderColor: 'rgba(245, 158, 11, 0.4)',
        elevation: 8,
        transform: [{ scale: 1.05 }],
    },
    statValue: {
        fontSize: 24,
        fontFamily: 'OutfitBold',
    },
    statLabel: {
        fontSize: 12,
        fontFamily: 'Outfit',
        color: '#64748B',
        marginTop: 2,
    },
    untrackedSection: {
        marginBottom: 32,
    },
    sectionTitle: {
        fontSize: 16,
        fontFamily: 'OutfitBold',
        color: '#475569',
        marginBottom: 12,
    },
    untrackedList: {
        gap: 12,
        paddingRight: 20,
    },
    untrackedCard: {
        backgroundColor: '#FFF',
        borderRadius: 20,
        padding: 16,
        width: 120,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#F1F5F9',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
    },
    untrackedIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    untrackedName: {
        fontSize: 14,
        fontFamily: 'OutfitBold',
        color: '#1E293B',
        marginBottom: 6,
    },
    enableLabel: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EEF2FF',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    enableText: {
        fontSize: 11,
        fontFamily: 'OutfitBold',
        color: '#4F46E5',
        marginLeft: 2,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    modalContent: {
        backgroundColor: '#FFF',
        borderRadius: 24,
        padding: 24,
        width: '100%',
        maxWidth: 400,
        maxHeight: '85%',
        elevation: 20,
        shadowColor: '#4F46E5',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.15,
        shadowRadius: 20,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        marginBottom: 24,
    },
    modalIconBg: {
        width: 56,
        height: 56,
        borderRadius: 16,
        backgroundColor: '#EEF2FF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 20,
        fontFamily: 'OutfitBold',
        color: '#111827',
    },
    modalSubtitle: {
        fontSize: 13,
        color: '#64748B',
        fontFamily: 'Outfit',
        marginTop: 2,
    },
    modalForm: {
        gap: 16,
        marginBottom: 24,
    },
    inputGroup: {
        gap: 8,
    },
    inputLabel: {
        fontSize: 13,
        fontFamily: 'OutfitBold',
        color: '#475569',
        marginLeft: 4,
    },
    modalInput: {
        backgroundColor: '#F8FAFC',
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        fontFamily: 'Outfit',
        color: '#1E293B',
        borderWidth: 1.5,
        borderColor: '#E2E8F0',
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButton: {
        backgroundColor: '#F1F5F9',
    },
    cancelButtonText: {
        color: '#64748B',
        fontFamily: 'OutfitBold',
        fontSize: 15,
    },
    confirmButton: {
        backgroundColor: '#4F46E5',
    },
    confirmButtonText: {
        color: '#FFF',
        fontFamily: 'OutfitBold',
        fontSize: 15,
    },
    batchesContainer: {
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#F3F4F6',
    },
    progressBar: {
        height: 12,
        backgroundColor: '#E5E7EB',
        borderRadius: 6,
        flexDirection: 'row',
        overflow: 'hidden',
        marginBottom: 12,
    },
    progressSegment: {
        height: '100%',
        borderRightWidth: 1,
        borderRightColor: '#FFF',
    },
    batchesList: {
        gap: 8,
    },
    batchRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    batchDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 8,
    },
    batchQuantityText: {
        fontSize: 14,
        fontFamily: 'OutfitBold',
        color: '#374151',
        width: 60,
    },
    batchExpiryText: {
        fontSize: 14,
        fontFamily: 'Outfit',
        color: '#6B7280',
        flex: 1,
    },
    batchTag: {
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    batchTagText: {
        fontSize: 10,
        fontFamily: 'OutfitBold',
        textTransform: 'uppercase',
    },
});
